### ISSUE TITLE
Change default='no's and 'yes's to default=False and default=True

### ISSUE THREAD

**Issue by aminvakil** [ansible-collections/community.general#550]
##### SUMMARY
Change all `default='no'`s to `default=False` in modules, when their variable type is boolean.
https://github.com/ansible-collections/community.general/pull/548#discussion_r443220237

Same for `default='yes'`s to `default=True`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
collection

**Comment by felixfontein** [comment]
For the apk module, there are some more violated sanity check rules:
```
plugins/modules/packaging/os/apk.py validate-modules:doc-choices-do-not-match-spec
plugins/modules/packaging/os/apk.py validate-modules:doc-missing-type
plugins/modules/packaging/os/apk.py validate-modules:parameter-list-no-elements
plugins/modules/packaging/os/apk.py validate-modules:parameter-type-not-in-doc
```
(See tests/sanity/ignore*.txt)

**Comment by aminvakil** [comment]
I meant this issue to be more general about all modules, now I got confused, should this be about `apk` ignored tests too?

**Comment by felixfontein** [comment]
The issue for all modules is kind of "tracked" in the ignore.txt lines already. I assumed you created this issue because of my comment for the apk module, so the main aim of this issue is for the apk module (or similar ones).

There are quite many modules which were never adjusted to more rigorous sanity tests (hence the large amount of ignore.txt lines - most of them are because of that). If you want to improve some of them, feel free! It definitely improves the modules (and depending on the error, the module docs).
