### ISSUE TITLE
community.general.ansible_galaxy_install  : collection can not be used in the same playbook

### ISSUE THREAD

**Issue by fletort** [ansible-collections/community.general#6628]
### Summary

When i am using community.general.ansible_galaxy_install to install a collaction dynamically from my playbook. this collection can not be used in the same playbook (with a include_role after).

From this playbook, if i try to list collection by calling ansible-galaxy list with the cmd module, this new collection is listed.

But if i try to see if this collection is known with the collection_version_lookup, the collection is not found.

This feature was possible with simple role outside of collection (import role with ansible_galaxy_install  and use it in the same playbook).

### Issue Type

Bug Report

### Component Name

ansible_galaxy_install

### Ansible Version

2.12.3

### Community.general Version

5.5.0

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

When i am using community.general.ansible_galaxy_install to install a collaction dynamically from my playbook. this collection can not be used in the same playbook (with a include_role after).

### Expected Results

Role from this collection added with a call to ansible_galaxy_install must be available to be call by an include_role in the same playbook.

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by felixfontein** [comment]
That's due to how ansible-core works. I don't think we can change that (from community.general's point of view).

**Comment by fletort** [comment]
Maybe i should post a request on ansible core side ... Because collection
should give the same freedoom than role alone...

Le mar. 6 juin 2023 à 20:48, Felix Fontein ***@***.***> a
écrit :

**Comment by felixfontein** [comment]
Basically the ansible_galaxy_install module does the same thing as `command: ansible-galaxy collection install ...`, just in an idempotent way.

AFAIK the collection loader looks for collections when ansible-core is started, and will not update that information during runtime. That's why another invocation of `ansible-galaxy collection list` will show you the new collection, but the ansible-core instance already running doesn't see it.

For roles I guess the finding mechanism was different (search for the role when it is first used, instead of finding them all on startup), that's why it does work for roles but not for collections. In any case, the only folks who can change this behavior is the core team, though I doubt that they will change it.

I'm closing this issue as there is nothing we can do here.
